package brain

import (
	"context"
	"fmt"
	"log"
)

// Brainstem Represents the Foundation, Safety, and Physical Execution Layer (Motor)
//
// Role:
//   - "Survival and Instinct".
//   - Holds the final authority on execution (Safety Interception).
//   - Executes concrete system calls, file I/O, and shell commands.
//   - Connects to external buses (e.g., Cosmos-star, NATS).
//
// Rule:
//   - The Brain (Cerebrum/Cerebellum) proposes; the Brainstem disposes.
//   - It can veto any action proposed by the higher cognitive layers if deemed unsafe.
//
// Analogy:
//   The physical motor cortex and autonomic nervous system.

type Brainstem interface {
	// Execute performs a concrete action (e.g., a tool call) after passing safety checks.
	Execute(ctx context.Context, action string, params map[string]any) (string, error)

	// Veto evaluates an intended action for safety violations.
	Veto(ctx context.Context, action string) bool
}

// TaskDispatcher acts as a dependency inversion interface, implemented by cosmos-star.
// It is responsible for dispatching logical tasks packaged by Cerebellum to specific physical or edge nodes for computation.
type TaskDispatcher interface {
	// Dispatch dispatches the job to the cosmos-star cluster for processing, returning a JobID generated by the underlying system.
	Dispatch(ctx context.Context, job JobPayload) (string, error)

	// WatchTask watches the execution flow and results of tasks on a computing node.
	WatchTask(ctx context.Context, jobID string) (<-chan JobResult, error)
}

// ClusterMonitor handles cluster and device health monitoring, provided by the cosmos-star topology network.
type ClusterMonitor interface {
	// GetNodeStatus retrieves the available computing nodes and devices within the current galaxy/cluster.
	GetNodeStatus(ctx context.Context) ([]NodeInfo, error)

	// Ping reports the current survival and health status of domour to the cosmos-star brainstem gateway.
	Ping(ctx context.Context, status AgentStatus) error
}

// EventBus represents the global event communication bus interface (publish-subscribe).
type EventBus interface {
	Publish(ctx context.Context, topic string, event []byte) error
	Subscribe(ctx context.Context, topic string, handler func(event []byte)) error
}

// PersistentStorage represents the underlying unified data persistence interface (database/KV, etc., injected by the infrastructure platform).
type PersistentStorage interface {
	SaveState(ctx context.Context, key string, data []byte) error
	LoadState(ctx context.Context, key string) ([]byte, error)
}

// NodeInfo represents the edge node information in the underlying cosmos-star cluster.
type NodeInfo struct {
	NodeID   string
	Role     string
	IsOnline bool
	Tags     map[string]string
}

// AgentStatus represents the health information of domour (Brain + Cerebellum) above.
type AgentStatus struct {
	Health        bool
	ActiveIntents int
	MemoryUsage   float64
}

// JobPayload represents the physical task package delivered by Cerebellum to the underlying execution layer.
type JobPayload struct {
	TaskNodeID string
	ToolName   string
	Arguments  []byte
}

// JobResult represents the result returned by the underlying edge node after execution.
type JobResult struct {
	JobID   string
	Success bool
	Output  []byte
	Error   string
}

// BrainstemNode is the execution and safety-interception event node for the Brainstem component.
// It runs a single goroutine that performs veto checks before executing any action,
// giving the Brainstem final authority over all physical/system operations.
//
// The Brainstem is the sole output gateway of the system (analogous to the human brainstem):
//   - Tool/system actions → FeedbackOut (internal correction loop back to Cerebellum)
//   - "respond" actions  → ResponseOut (external output to the caller)
//
// RouteFn is the neural signal routing function injected by the Runtime at assembly time.
type BrainstemNode struct {
	CommandIn   chan CognitiveResult
	PonsOut     chan CognitiveResult
	ResponseOut chan MotorFeedback // external: final output → Diencephalon
	RouteFn     func(ctx context.Context) // injected by Runtime
}

func NewBrainstemNode() *BrainstemNode {
	return &BrainstemNode{
		CommandIn:   make(chan CognitiveResult, 10),
		PonsOut:     make(chan CognitiveResult, 10),
		ResponseOut: make(chan MotorFeedback, 20),
	}
}

// Start launches the neural signal routing goroutine (via RouteFn) and the Pons loop.
// As the foundation layer, the Brainstem has final authority over both execution
// and the moment routing begins.
func (b *BrainstemNode) Start(ctx context.Context) {
	if b.RouteFn != nil {
		go b.RouteFn(ctx)
	}
	go b.startPonsLoop(ctx)
}

// startPonsLoop models the Pons (脑桥) splitting the command.
// If the command is a final respond answer (Intent == "respond"), it is directly routed
// to ResponseOut. Otherwise, the command is duplicated horizontally to the Cerebellum.
func (b *BrainstemNode) startPonsLoop(ctx context.Context) {
	log.Println("[Brainstem-Pons] Pons command splitter loop started.")
	for {
		select {
		case <-ctx.Done():
			log.Println("[Brainstem-Pons] Pons loop stopped.")
			return
		case cmd := <-b.CommandIn:
			log.Printf("[Brainstem-Pons] Command received: %s, Intent: %s", cmd.GoalID, cmd.Intent)

			if cmd.Intent == "respond" {
				log.Printf("[Brainstem] Rendering final response for Goal %s", cmd.GoalID)
				select {
				case b.ResponseOut <- MotorFeedback{
					ActionID: cmd.GoalID,
					Success:  true,
					Output:   fmt.Sprintf("%v", cmd.Plan),
				}:
				case <-ctx.Done():
					return
				}
				continue
			}

			log.Printf("[Brainstem-Pons] Eavesdropping copy generated for Command: %s", cmd.GoalID)
			select {
			case b.PonsOut <- cmd:
			case <-ctx.Done():
				return
			}
		}
	}
}

