package brain

import (
	"context"
	"time"
)

// Observation represents the external input or stimulus received by the brain.
type Observation struct {
	Source string
	Data   interface{}
}

// Intent represents the high-level intent issued by the brain after thinking.
type Intent struct {
	GoalID      string
	Description string
	Payload     map[string]interface{}
}

// MemoryPayload represents a memory fragment.
type MemoryPayload struct {
	ID        string
	Content   string
	Timestamp int64
	Tags      []string
}

// SystemHealthStatus represents the self-health status of the system inspected by the consciousness body.
type SystemHealthStatus struct {
	IsHealthy    bool
	MemoryUsage  float64
	ActiveMinds  int
	LastSelfDiag string
}


// Brain controls the center, exposing interaction entry points to other systems.
type Brain interface {
	// Think receives external events and observation results, performs reasoning based on memory and rules/LLM, and gives high-level intents.
	Think(ctx context.Context, observation Observation) (Intent, error)

	// Memorize stores information into memory (short-term or long-term).
	Memorize(ctx context.Context, info MemoryPayload) error

	// Recall retrieves memory from long-term or short-term cache.
	Recall(ctx context.Context, query string) ([]MemoryPayload, error)
}

// Consciousness controls the consciousness body: a constantly running daemon process that continuously examines the system's own status.
type Consciousness interface {
	// Start starts the autonomous inspection loop of consciousness.
	Start(ctx context.Context) error

	// Stop stops the inspection.
	Stop()

	// InspectSelf performs a self-status feedback review.
	InspectSelf() SystemHealthStatus
}


const LayerName = "brain"

// Thought is the smallest decision result output by the Brain to the downstream execution layer.
type Thought struct {
	Intent string            `json:"intent"`
	Route  string            `json:"route"`
	Plan   []string          `json:"plan,omitempty"`
	Risk   string            `json:"risk,omitempty"`
	Meta   map[string]string `json:"meta,omitempty"`
}

// Module defines the minimum responsibility of the Brain layer: understand goals, form plans, and make routing decisions.
type Module interface {
	Name() string
	Think(ctx context.Context, state State) (Thought, error)
}

// SensorySignal represents raw input data or stimulus received by the Diencephalon.
type SensorySignal struct {
	Ctx       context.Context
	SessionID string
	TopicID   string // Topic-scoped conversation ID, tracked by TopicDetector (e.g. "sess_abc:1")
	Topic     string // Human-readable topic label (top-3 terms)
	Source    string
	Data      interface{}
	Timestamp time.Time
}

// CognitiveTask represents a semantic thought request sent to the Cerebrum.
type CognitiveTask struct {
	Ctx     context.Context
	GoalID  string
	Prompt  string
	Context interface{}
}

// CognitiveResult represents the high-level intent and task sequence generated by the Cerebrum.
type CognitiveResult struct {
	GoalID string
	Intent string
	Plan   []string
}

// MemoryCommand represents a request to retrieve or persist memories asynchronously.
type MemoryCommand struct {
	Op      string // "store" or "recall"
	Payload MemoryPayload
	ReplyCh chan<- []MemoryPayload
}

// TacticalAction represents a concrete skill or tool action dispatched by the Cerebellum.
type TacticalAction struct {
	ActionID  string
	ToolName  string
	Arguments map[string]interface{}
}

// MotorFeedback represents the physical/system response received from the Brainstem.
type MotorFeedback struct {
	ActionID string
	Success  bool
	Output   string
	Err      error
}
